[pipelines] enhance reporting for pipelines

diff --git a/.buildkite/claim-settlements.yml b/.buildkite/claim-settlements.yml
--- a/.buildkite/claim-settlements.yml
+++ b/.buildkite/claim-settlements.yml
@@ -146,7 +146,6 @@ steps:
         echo 'No claimable settlement to claim from' | tee ./claiming-report.txt
         exit 0
       fi
-    - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name" . || true
     - buildkite-agent artifact download --include-retried-jobs target/release/claim-settlement .
     - chmod +x target/release/claim-settlement
     - |
@@ -162,7 +161,6 @@ steps:
         fi
       done
     - source ./scripts/execute-handlers.sh
-    - trap 'cat "./execution-report.$${command_name}.$$BUILDKITE_RETRY_COUNT" >> "./execution-report.$${command_name}"' EXIT
     - |
       handle_command_execution "$$command_name" \
       ./target/release/claim-settlement \
@@ -172,7 +170,7 @@ steps:
         $$files
     depends_on: "download-merkle-trees"
     artifact_paths:
-      - "./execution-report*"
+      - "./report.*.json"
     retry:
       automatic:
         - exit_status: 100
@@ -181,11 +179,15 @@ steps:
   - label: ":memo: Notification setup: Claim Settlements"
     key: "notification-setup-claim"
     commands:
-     - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name" . || echo "No report ERROR" > ./execution-report.$$command_name
-     - cp "./execution-report.$$command_name" "./cumulative-report.$${command_name}.txt"
-     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c ATTEMPT ./cumulative-report.$${command_name}.txt)"
+    - |
+      buildkite-agent artifact download --include-retried-jobs "report.$$command_name.*.json" . || \
+        echo '{"command":"'$$command_name'","status":{"success":false,"error_count":1},"summary":"No report found"}' > "./report.$$command_name.0.json"
+    - latest_report=$$(ls -v "report.$$command_name."[0-9]*.json 2>/dev/null | tail -n 1)
+    - cp "$$latest_report" "./cumulative-report.$${command_name}.json"
+    - attempts_count=$$(ls -1 "report.$$command_name."[0-9]*.json 2>/dev/null | wc -l)
+    - buildkite-agent meta-data set --redacted-vars="" attempts_count "$$attempts_count"
     artifact_paths:
-      - "./cumulative-report.*"
+      - "./cumulative-report.*.json"
     depends_on: "claim-settlement"
     allow_dependency_failure: true
 
@@ -193,9 +195,7 @@ steps:
     key: "annotate-report-claim"
     commands:
       - source ./scripts/execute-handlers.sh
-      - annotate_execution_report "$$command_name" 20
-    artifact_paths:
-      - "./latest-report.txt"
+      - annotate_execution_report "$$command_name"
     depends_on: "claim-settlement"
     allow_dependency_failure: true
 
@@ -203,12 +203,12 @@ steps:
 
   - label: ":floppy_disk: :arrow_right: :cloud: Upload artifacts Claim Settlements"
     commands:
-    - buildkite-agent artifact download cumulative-report.$${command_name}.txt . || echo "UNKNOWN ERROR" > ./cumulative-report.$${command_name}.txt
+    - buildkite-agent artifact download cumulative-report.$${command_name}.json . || echo '"UNKNOWN ERROR"' > ./cumulative-report.$${command_name}.json
     - claimable_epochs_json=$(buildkite-agent meta-data get claimable_epochs_json)
     - first_epoch=$(echo "$$claimable_epochs_json" | jq ".[0]")
     - |
       if [[ -n "$$first_epoch" && "$$first_epoch" != "null" && $(gcloud storage ls "$gs_bucket/$$first_epoch" 2> /dev/null) ]]; then
-        gcloud storage cp ./cumulative-report.$${command_name}.txt "$gs_bucket/$$first_epoch/buildkite/$${command_name}-report.$(date +%s).txt"
+        gcloud storage cp ./cumulative-report.$${command_name}.json "$gs_bucket/$$first_epoch/buildkite/$${command_name}-report.$(date +%s).json"
       fi
     depends_on: "notification-setup-claim"
     allow_dependency_failure: true
