[buildkite] annotate results

diff --git a/.buildkite/claim-settlements.yml b/.buildkite/claim-settlements.yml
--- a/.buildkite/claim-settlements.yml
+++ b/.buildkite/claim-settlements.yml
@@ -4,6 +4,7 @@ agents:
 env:
   gs_bucket: gs://marinade-validator-bonds-mainnet
   SLACK_API: https://slack.com/api/chat.postMessage
+  command_name: 'claim-settlement'
 
 steps:
   - label: ":closed_lock_with_key: Concurrency gate claim-settlements lock"
@@ -55,7 +56,7 @@ steps:
       - claim_type=${CLAIM_TYPE:-$(buildkite-agent meta-data get claim_type)}
       - slack_feed=$(buildkite-agent meta-data get slack_feed)
       - |
-        cat <<- EOF | buildkite-agent annotate --style info --context "general-info"
+        cat <<- EOF | buildkite-agent annotate --priority 6 --style info --context "general-info"
         ### Retry environment variables
         If you need to retry the build, use the following parameters:
 
@@ -142,13 +143,7 @@ steps:
         echo 'No claimable settlement to claim from' | tee ./claiming-report.txt
         exit 0
       fi
-    - prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))
-    - command_name='claim-settlement'
-    - buildkite-agent artifact download --include-retried-jobs execution-report.$$command_name.$$prior_build_number . || true
-    - |
-      cp "execution-report.$$command_name.$$prior_build_number" "execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT" || true
-      rm -f "execution-report.$$command_name.$$prior_build_number"
-      echo "#ATTEMPT CLAIM SETTLEMENTS $$BUILDKITE_RETRY_COUNT" | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
+    - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name" . || true
     - buildkite-agent artifact download --include-retried-jobs target/release/claim-settlement .
     - chmod +x target/release/claim-settlement
     - |
@@ -164,8 +159,9 @@ steps:
         fi
       done
     - source ./scripts/execute-handlers.sh
+    - trap 'cat "./execution-report.$${command_name}.$$BUILDKITE_RETRY_COUNT" >> "./execution-report.$${command_name}"' EXIT
     - |
-      handle_command_execution "claim-settlement" \
+      handle_command_execution "$$command_name" \
       ./target/release/claim-settlement \
         --config $(buildkite-agent meta-data get config_pubkey) \
         --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
@@ -173,7 +169,7 @@ steps:
         $$files
     key: 'claim-settlement'
     artifact_paths:
-    - "./execution-report.*"
+      - "./execution-report*"
     retry:
       automatic:
         - exit_status: 100
@@ -181,15 +177,22 @@ steps:
 
   - label: ":memo: Notification setup: Claim Settlements"
     commands:
-     - mkdir ./reports
-     - command_name='claim-settlement'
-     - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.$$command_name.error
-     - report_path="./reports/$(ls -v1 reports/ | tail -n 1)"
-     - cp "$$report_path" ./claiming-report.txt
-     - buildkite-agent meta-data set --redacted-vars='' attempts_count "$(grep -c ATTEMPT ./claiming-report.txt)"
+     - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name" . || echo "No report ERROR" > ./execution-report.$$command_name
+     - cp "./execution-report.$$command_name" "./cumulative-report.txt"
+     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c ATTEMPT ./cumulative-report.txt)"
     artifact_paths:
-    - "./claiming-report.txt"
+      - "./cumulative-report.txt"
     key: 'notification-setup-claim'
+    depends_on: "claim-settlement"
+    allow_dependency_failure: true
+
+  - label: ":printer: Annotate Report"
+    commands:
+      - source ./scripts/execute-handlers.sh
+      - annotate_execution_report "$$command_name" 20
+    artifact_paths:
+      - "./latest-report.txt"
+    key: 'annotate-report-claim'
     depends_on: "claim-settlement"
     allow_dependency_failure: true
 
@@ -197,23 +200,20 @@ steps:
 
   - label: ":floppy_disk: :arrow_right: :cloud: Upload artifacts Claim Settlements"
     commands:
-    - buildkite-agent artifact download --include-retried-jobs claiming-report.txt . || echo "UNKNOWN ERROR" > claiming-report.txt
+    - buildkite-agent artifact download cumulative-report.txt . || echo "UNKNOWN ERROR" > ./cumulative-report.txt
     - claimable_epochs_json=$(buildkite-agent meta-data get claimable_epochs_json)
     - first_epoch=$(echo "$$claimable_epochs_json" | jq ".[0]")
     - |
       if [[ -n "$$first_epoch" && "$$first_epoch" != "null" && $(gcloud storage ls "$gs_bucket/$$first_epoch" 2> /dev/null) ]]; then
-        gcloud storage cp ./claiming-report.txt "$gs_bucket/$$first_epoch/buildkite/claiming-report.$(date +%s).txt"
+        gcloud storage cp ./cumulative-report.txt "$gs_bucket/$$first_epoch/buildkite/$${command_name}-report.$(date +%s).txt"
       fi
     depends_on: "notification-setup-claim"
     allow_dependency_failure: true
 
   - label: ":mega: Notification Claiming"
     commands:
-    - buildkite-agent artifact download --include-retried-jobs claiming-report.txt . || echo "UNKNOWN ERROR" > claiming-report.txt
-    - cat ./claiming-report.txt
-    - echo "--------------------------------------------"
     - source ./scripts/execute-handlers.sh
-    - check_command_execution_status "claim-settlement" || true
+    - check_command_execution_status "$$command_name" || true
     - claim_type=$(buildkite-agent meta-data get claim_type)
     - config_pubkey=$(buildkite-agent meta-data get config_pubkey)
     - attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
diff --git a/.buildkite/fund-settlements.yml b/.buildkite/fund-settlements.yml
--- a/.buildkite/fund-settlements.yml
+++ b/.buildkite/fund-settlements.yml
@@ -46,7 +46,7 @@ steps:
       slack_feed=$(./scripts/bonds-slack-feed.sh "$$claim_type")
       buildkite-agent meta-data set --redacted-vars='' slack_feed "$$slack_feed"
     - |
-      echo "Epoch: '$$epoch', Claim Type: '$$claim_type'/'$$config_pubkey', Slack Feed: '$$slack_feed'"
+      echo "Epoch: '$${epoch:-unknown}', Claim Type: '$$claim_type'/'$$config_pubkey', Slack Feed: '$$slack_feed'"
 
   - wait: ~
 
@@ -105,17 +105,12 @@ steps:
 
   - label: ":campfire::arrow_right: Fund settlements"
     env:
+      command_name: 'fund-settlement'
       RPC_URL: "$$RPC_URL"
       RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,solana_transaction_executor=debug,fund_settlement=debug
     commands:
     - . "$HOME/.cargo/env"
-    - prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))
-    - command_name='fund-settlement'
-    - buildkite-agent artifact download --include-retried-jobs execution-report.$$command_name.$$prior_build_number . || true
-    - |
-      cp "execution-report.$$command_name.$$prior_build_number" "execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT" || true
-      rm -f "execution-report.$$command_name.$$prior_build_number"
-      echo "#ATTEMPT FUND SETTLEMENT $$BUILDKITE_RETRY_COUNT" | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
+    - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name" . || true
     - |
       buildkite-agent artifact download --include-retried-jobs "merkle-trees/*" .
       files=""
@@ -131,6 +126,7 @@ steps:
     - buildkite-agent artifact download --include-retried-jobs target/release/fund-settlement .
     - chmod +x target/release/fund-settlement
     - source ./scripts/execute-handlers.sh
+    - trap 'cat "./execution-report.$${command_name}.$$BUILDKITE_RETRY_COUNT" >> "./execution-report.$${command_name}"' EXIT
     - |
       handle_command_execution "$$command_name" \
       ./target/release/fund-settlement \
@@ -142,23 +138,34 @@ steps:
         $$files
     key: 'fund-settlement'
     artifact_paths:
-      - "./execution-report.*"
+      - "./execution-report*"
     retry:
       automatic:
         - exit_status: 100
           limit: 5
 
   - label: ":memo: Notification setup: Fund Settlements"
+    env:
+      command_name: 'fund-settlement'
     commands:
-     - mkdir ./reports
-     - command_name='fund-settlement'
-     - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.$$command_name.error
-     - report_path="./reports/$(ls -v1 reports/ | tail -n 1)"
-     - cp "$$report_path" ./fund-report.txt
-     - buildkite-agent meta-data set --redacted-vars='' attempts_count "$(grep -c ATTEMPT ./fund-report.txt)"
+     - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name" . || echo "No report ERROR" > ./execution-report.$$command_name
+     - cp "./execution-report.$$command_name" "./cumulative-report.txt"
+     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c ATTEMPT ./cumulative-report.txt)"
     artifact_paths:
-    - "./fund-report.txt"
+      - "./cumulative-report.txt"
     key: 'notification-setup-funding'
+    depends_on: "fund-settlement"
+    allow_dependency_failure: true
+
+  - label: ":printer: Annotate Report"
+    env:
+      command_name: 'fund-settlement'
+    commands:
+      - source ./scripts/execute-handlers.sh
+      - annotate_execution_report "$$command_name" 20
+    artifact_paths:
+      - "./latest-report.txt"
+    key: 'annotate-report-fund'
     depends_on: "fund-settlement"
     allow_dependency_failure: true
 
@@ -169,21 +176,20 @@ steps:
     - latest_funded_epoch=$(buildkite-agent meta-data get latest_funded_epoch) || true
     - claim_type=$(buildkite-agent meta-data get claim_type) || true
     - claim_type_prefix=$([[ -z "$$claim_type" ]] && echo "" || echo "$${claim_type}-")
-    - buildkite-agent artifact download --include-retried-jobs fund-report.txt . || echo "UNKNOWN ERROR" > fund-report.txt
+    - buildkite-agent artifact download cumulative-report.txt . || echo "UNKNOWN ERROR" > ./cumulative-report.txt
     - |
       if [[ -n "$$latest_funded_epoch" && $(gcloud storage ls "$gs_bucket/$$latest_funded_epoch" 2> /dev/null) ]]; then
-        gcloud storage cp ./fund-report.txt "$gs_bucket/$$latest_funded_epoch/buildkite/$${claim_type_prefix}fund-settlement-report.$(date +%s).txt"
+        gcloud storage cp ./cumulative-report.txt "$gs_bucket/$$latest_funded_epoch/buildkite/$${claim_type_prefix}$${command_name}-report.$(date +%s).txt"
       fi
     depends_on: "notification-setup-funding"
     allow_dependency_failure: true
 
   - label: ":mega: Notification Funding"
+    env:
+      command_name: 'fund-settlement'
     commands:
-    - buildkite-agent artifact download --include-retried-jobs fund-report.txt . || echo 'UNKNOWN ERROR' > './fund-report.txt'
-    - cat ./fund-report.txt
-    - echo "--------------------------------------------"
     - source ./scripts/execute-handlers.sh
-    - check_command_execution_status "fund-settlement" || true
+    - check_command_execution_status "$$command_name" || true
     - claim_type=$(buildkite-agent meta-data get claim_type)
     - config_pubkey=$(buildkite-agent meta-data get config_pubkey)
     - attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
