[pipelines] cummulative report fix upload [trivial] (#336)
* [pipelines] cummulative report fix upload

* [review] fixes

diff --git a/.buildkite/claim-settlements.yml b/.buildkite/claim-settlements.yml
--- a/.buildkite/claim-settlements.yml
+++ b/.buildkite/claim-settlements.yml
@@ -177,10 +177,10 @@ steps:
   - label: ":memo: Notification setup: Claim Settlements"
     commands:
      - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name" . || echo "No report ERROR" > ./execution-report.$$command_name
-     - cp "./execution-report.$$command_name" "./cumulative-report.txt"
-     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c ATTEMPT ./cumulative-report.txt)"
+     - cp "./execution-report.$$command_name" "./cumulative-report.$${command_name}.txt"
+     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c ATTEMPT ./cumulative-report.$${command_name}.txt)"
     artifact_paths:
-      - "./cumulative-report.txt"
+      - "./cumulative-report.*"
     key: 'notification-setup-claim'
     depends_on: "claim-settlement"
     allow_dependency_failure: true
@@ -199,12 +199,12 @@ steps:
 
   - label: ":floppy_disk: :arrow_right: :cloud: Upload artifacts Claim Settlements"
     commands:
-    - buildkite-agent artifact download cumulative-report.txt . || echo "UNKNOWN ERROR" > ./cumulative-report.txt
+    - buildkite-agent artifact download cumulative-report.$${command_name}.txt . || echo "UNKNOWN ERROR" > ./cumulative-report.$${command_name}.txt
     - claimable_epochs_json=$(buildkite-agent meta-data get claimable_epochs_json)
     - first_epoch=$(echo "$$claimable_epochs_json" | jq ".[0]")
     - |
       if [[ -n "$$first_epoch" && "$$first_epoch" != "null" && $(gcloud storage ls "$gs_bucket/$$first_epoch" 2> /dev/null) ]]; then
-        gcloud storage cp ./cumulative-report.txt "$gs_bucket/$$first_epoch/buildkite/$${command_name}-report.$(date +%s).txt"
+        gcloud storage cp ./cumulative-report.$${command_name}.txt "$gs_bucket/$$first_epoch/buildkite/$${command_name}-report.$(date +%s).txt"
       fi
     depends_on: "notification-setup-claim"
     allow_dependency_failure: true
diff --git a/.buildkite/fund-settlements.yml b/.buildkite/fund-settlements.yml
--- a/.buildkite/fund-settlements.yml
+++ b/.buildkite/fund-settlements.yml
@@ -150,10 +150,10 @@ steps:
       command_name: 'fund-settlement'
     commands:
      - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name" . || echo "No report ERROR" > ./execution-report.$$command_name
-     - cp "./execution-report.$$command_name" "./cumulative-report.txt"
-     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c ATTEMPT ./cumulative-report.txt)"
+     - cp "./execution-report.$$command_name" "./"
+     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c ATTEMPT ./cumulative-report.$${command_name}.txt)"
     artifact_paths:
-      - "./cumulative-report.txt"
+      - "./cumulative-report.*"
     key: 'notification-setup-funding'
     depends_on: "fund-settlement"
     allow_dependency_failure: true
@@ -177,10 +177,10 @@ steps:
     - latest_funded_epoch=$(buildkite-agent meta-data get latest_funded_epoch) || true
     - claim_type=$(buildkite-agent meta-data get claim_type) || true
     - claim_type_prefix=$([[ -z "$$claim_type" ]] && echo "" || echo "$${claim_type}-")
-    - buildkite-agent artifact download cumulative-report.txt . || echo "UNKNOWN ERROR" > ./cumulative-report.txt
+    - buildkite-agent artifact download cumulative-report.$${command_name}.txt . || echo "UNKNOWN ERROR" > ./cumulative-report.$${command_name}.txt
     - |
       if [[ -n "$$latest_funded_epoch" && $(gcloud storage ls "$gs_bucket/$$latest_funded_epoch" 2> /dev/null) ]]; then
-        gcloud storage cp ./cumulative-report.txt "$gs_bucket/$$latest_funded_epoch/buildkite/$${claim_type_prefix}$${command_name}-report.$(date +%s).txt"
+        gcloud storage cp ./cumulative-report.$${command_name}.txt "$gs_bucket/$$latest_funded_epoch/buildkite/$${claim_type_prefix}$${command_name}-report.$(date +%s).txt"
       fi
     depends_on: "notification-setup-funding"
     allow_dependency_failure: true
