[buildkite] differentiate name of execute log in pipeline definitions

diff --git a/.buildkite/claim-settlements.yml b/.buildkite/claim-settlements.yml
--- a/.buildkite/claim-settlements.yml
+++ b/.buildkite/claim-settlements.yml
@@ -99,19 +99,20 @@ steps:
       RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,builder_executor=debug,solana_transaction_executor=debug,settlement_pipelines=debug,claim_settlement=debug
       # RUST_BACKTRACE: full
     commands:
-    - '. "$HOME/.cargo/env"'
+    - . "$HOME/.cargo/env"
     - |
       claimable_epochs_num=$(buildkite-agent meta-data get claimable_epochs_num || echo "0")
       if [[ $$claimable_epochs_num -eq 0 ]]; then
         echo 'No claimable settlement to claim from' | tee ./claiming-report.txt
         exit 0
       fi
-    - 'prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))'
-    - 'buildkite-agent artifact download --include-retried-jobs execution-report.$$prior_build_number . || true'
+    - prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))
+    - command_name='claim-settlement'
+    - buildkite-agent artifact download --include-retried-jobs execution-report.$$command_name.$$prior_build_number . || true
     - |
-      cp "execution-report.$$prior_build_number" "execution-report.$$BUILDKITE_RETRY_COUNT" || true
-      rm -f "execution-report.$$prior_build_number"
-      echo "#ATTEMPT CLAIM SETTLEMENTS $$BUILDKITE_RETRY_COUNT" | tee -a "./execution-report.$$BUILDKITE_RETRY_COUNT"
+      cp "execution-report.$$command_name.$$prior_build_number" "execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT" || true
+      rm -f "execution-report.$$command_name.$$prior_build_number"
+      echo "#ATTEMPT CLAIM SETTLEMENTS $$BUILDKITE_RETRY_COUNT" | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
     - 'buildkite-agent artifact download --include-retried-jobs target/release/claim-settlement .'
     - 'chmod +x target/release/claim-settlement'
     - |
@@ -144,11 +145,12 @@ steps:
 
   - label: ":memo: Notification setup: Claim Settlements"
     commands:
-     - 'mkdir ./reports'
-     - 'buildkite-agent artifact download --include-retried-jobs "execution-report.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.error'
-     - 'report_path="./reports/$(ls -v1 reports/ | tail -n 1)"'
-     - 'cp "$$report_path" ./claiming-report.txt'
-     - 'buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./claiming-report.txt)"'
+     - mkdir ./reports
+     - command_name='claim-settlement'
+     - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.$$command_name.error
+     - report_path="./reports/$(ls -v1 reports/ | tail -n 1)"
+     - cp "$$report_path" ./claiming-report.txt
+     - buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./claiming-report.txt)"
     artifact_paths:
     - "./claiming-report.txt"
     key: 'notification-setup-claim'
diff --git a/.buildkite/close-settlements.yml b/.buildkite/close-settlements.yml
--- a/.buildkite/close-settlements.yml
+++ b/.buildkite/close-settlements.yml
@@ -77,16 +77,17 @@ steps:
       RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,solana_transaction_executor=debug,close_settlement=debug
       # RUST_BACKTRACE: full
     commands:
-    - '. "$HOME/.cargo/env"'
-    - 'prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))'
-    - 'buildkite-agent artifact download --include-retried-jobs close-execution-report.$$prior_build_number . || true'
+    - . "$HOME/.cargo/env"
+    - prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))
+    - command_name='close-settlement'
+    - buildkite-agent artifact download --include-retried-jobs execution-report.$$command_name.$$prior_build_number . || true
     - |
-      cp "close-execution-report.$$prior_build_number" "close-execution-report.$$BUILDKITE_RETRY_COUNT" || true
-      rm -f "close-execution-report.$$prior_build_number"
-      echo "#ATTEMPT CLOSE SETTLEMENTS $$BUILDKITE_RETRY_COUNT" | tee -a "./close-execution-report.$$BUILDKITE_RETRY_COUNT"
-    - 'buildkite-agent artifact download --include-retried-jobs target/release/close-settlement .'
-    - 'buildkite-agent artifact download --include-retried-jobs past-settlements.json .'
-    - 'chmod +x target/release/close-settlement'
+      cp "execution-report.$$command_name.$$prior_build_number" "execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT" || true
+      rm -f "execution-report.$$command_name.$$prior_build_number"
+      echo "#ATTEMPT CLOSE SETTLEMENTS $$BUILDKITE_RETRY_COUNT" | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
+    - buildkite-agent artifact download --include-retried-jobs target/release/close-settlement .
+    - buildkite-agent artifact download --include-retried-jobs past-settlements.json .
+    - chmod +x target/release/close-settlement
     - |
       set -o pipefail
       ./target/release/close-settlement \
@@ -94,10 +95,10 @@ steps:
         --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
         --fee-payer "$$PSR_TX_FEE_WALLET" \
         --marinade-wallet "$$PSR_MARINADE_DAO_FUNDER_WALLET" \
-        --past-settlements ./past-settlements.json | tee -a "./close-execution-report.$$BUILDKITE_RETRY_COUNT"
+        --past-settlements ./past-settlements.json | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
     key: 'close-settlement'
     artifact_paths:
-      - "./close-execution-report.*"
+      - "./execution-report.*"
     retry:
       automatic:
         - exit_status: 100
@@ -105,11 +106,12 @@ steps:
 
   - label: ":memo: Notification setup: Close Settlements"
     commands:
-    - 'mkdir ./reports'
-    - 'buildkite-agent artifact download --include-retried-jobs "close-execution-report.*" ./reports/ || echo "No report ERROR" > ./reports/close-execution-report.error'
-    - 'report_path="./reports/$(ls -v1 reports/ | tail -n 1)"'
-    - 'cp "$$report_path" ./close-report.txt'
-    - 'buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./close-report.txt)"'
+    - mkdir ./reports
+    - command_name='close-settlement'
+    - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.$$command_name.error
+    - report_path="./reports/$(ls -v1 reports/ | tail -n 1)"
+    - cp "$$report_path" ./close-report.txt
+    - buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./close-report.txt)"
     artifact_paths:
     - "./close-report.txt"
     key: 'notification-setup-close'
diff --git a/.buildkite/fund-settlements.yml b/.buildkite/fund-settlements.yml
--- a/.buildkite/fund-settlements.yml
+++ b/.buildkite/fund-settlements.yml
@@ -105,13 +105,14 @@ steps:
     env:
       RUST_LOG: info,solana_transaction_builder_executor=debug,solana_transaction_builder=debug,solana_transaction_executor=debug,fund_settlement=debug
     commands:
-    - '. "$HOME/.cargo/env"'
-    - 'prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))'
-    - 'buildkite-agent artifact download --include-retried-jobs execution-report.$$prior_build_number . || true'
+    - . "$HOME/.cargo/env"
+    - prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))
+    - command_name='fund-settlement'
+    - buildkite-agent artifact download --include-retried-jobs execution-report.$$command_name.$$prior_build_number . || true
     - |
-      cp "execution-report.$$prior_build_number" "execution-report.$$BUILDKITE_RETRY_COUNT" || true
-      rm -f "fund-execution-report.$$prior_build_number"
-      echo "#ATTEMPT FUND SETTLEMENT $$BUILDKITE_RETRY_COUNT" | tee -a "./execution-report.$$BUILDKITE_RETRY_COUNT"
+      cp "execution-report.$$command_name.$$prior_build_number" "execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT" || true
+      rm -f "fund-execution-report.$$command_name.$$prior_build_number"
+      echo "#ATTEMPT FUND SETTLEMENT $$BUILDKITE_RETRY_COUNT" | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
     - |
       buildkite-agent artifact download --include-retried-jobs "merkle-trees/*" .
       files=""
@@ -124,11 +125,11 @@ steps:
           files="$$files -f $$pair_files"
         fi
       done
-    - 'buildkite-agent artifact download --include-retried-jobs target/release/fund-settlement .'
-    - 'chmod +x target/release/fund-settlement'
+    - buildkite-agent artifact download --include-retried-jobs target/release/fund-settlement .
+    - chmod +x target/release/fund-settlement
     - source ./scripts/execute-handlers.sh
     - |
-      handle_command_execution "fund-settlement" \
+      handle_command_execution "$$command_name" \
       ./target/release/fund-settlement \
         --rpc-url $$RPC_URL \
         --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
@@ -147,7 +148,8 @@ steps:
   - label: ":memo: Notification setup: Fund Settlements"
     commands:
      - mkdir ./reports
-     - buildkite-agent artifact download --include-retried-jobs "execution-report-fund.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report-fund.error
+     - command_name='fund-settlement'
+     - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.$$command_name.error
      - report_path="./reports/$(ls -v1 reports/ | tail -n 1)"
      - cp "$$report_path" ./fund-report.txt
      - buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./fund-report.txt)"
diff --git a/.buildkite/init-settlements.yml b/.buildkite/init-settlements.yml
--- a/.buildkite/init-settlements.yml
+++ b/.buildkite/init-settlements.yml
@@ -112,11 +112,12 @@ steps:
     - . "$HOME/.cargo/env"
     - epoch=$(buildkite-agent meta-data get epoch)
     - prior_build_number=$(($$BUILDKITE_RETRY_COUNT - 1))
-    - buildkite-agent artifact download --include-retried-jobs init-execution-report.$$prior_build_number . || true
+    - command_name='init-settlement'
+    - buildkite-agent artifact download --include-retried-jobs execution-report.$$command_name.$$prior_build_number . || true
     - |
-      cp "init-execution-report.$$prior_build_number" "init-execution-report.$$BUILDKITE_RETRY_COUNT" || true
-      rm -f "init-execution-report.$$prior_build_number"
-      echo "#ATTEMPT INIT SETTLEMENTS $$BUILDKITE_RETRY_COUNT" | tee -a "./init-execution-report.$$BUILDKITE_RETRY_COUNT"
+      cp "execution-report.$$command_name.$$prior_build_number" "execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT" || true
+      rm -f "execution-report.$$command_name.$$prior_build_number"
+      echo "#ATTEMPT INIT SETTLEMENTS $$BUILDKITE_RETRY_COUNT" | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
     - buildkite-agent artifact download --include-retried-jobs target/release/init-settlement .
     - buildkite-agent artifact download --include-retried-jobs settlement-merkle-trees.json .
     - buildkite-agent artifact download --include-retried-jobs settlements.json .
@@ -130,10 +131,10 @@ steps:
         --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
         --fee-payer "$$PSR_TX_FEE_WALLET" \
         --rent-payer "$$PSR_RENT_PAYER_WALLET" \
-        --epoch "$$epoch" | tee -a "./init-execution-report.$$BUILDKITE_RETRY_COUNT"
+        --epoch "$$epoch" | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
     key: 'init-settlement'
     artifact_paths:
-    - "./init-execution-report.*"
+    - "./execution-report.*"
     retry:
       automatic:
         - exit_status: 100
@@ -155,7 +156,8 @@ steps:
      - buildkite-agent meta-data set notification_result "$$notification_result"
      - 'echo "Notification result: $$notification_result, color: $$notification_color"'
      - mkdir ./reports
-     - buildkite-agent artifact download --include-retried-jobs "init-execution-report.*" ./reports/ || echo "No report ERROR" > ./reports/init-execution-report.error
+     - command_name='init-settlement'
+     - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.$$command_name.error
      - report_path="./reports/$(ls -v1 reports/ | tail -n 1)"
      - cp "$$report_path" ./init-report.txt
      - buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./init-report.txt)"
