[settlement-pipeline] init settlement refactoring

diff --git a/.buildkite/claim-settlements.yml b/.buildkite/claim-settlements.yml
--- a/.buildkite/claim-settlements.yml
+++ b/.buildkite/claim-settlements.yml
@@ -91,7 +91,7 @@ steps:
     retry:
       automatic:
         - exit_status: 100
-          limit: 10
+          limit: 5
 
   - label: "Notification setup"
     env:
@@ -99,7 +99,7 @@ steps:
     commands:
      - |
        build_result=$(buildkite-agent step get "outcome" --step "claim-settlement")
-        if [[ "$$build_result" =~ "failed" ]]; then
+        if [[ -z "$$build_result" || "$$build_result" =~ "failed" ]]; then
           notification_result="FAILED"
           notification_color="15158332"
         else
@@ -112,19 +112,19 @@ steps:
      - 'mkdir ./reports'
      - 'buildkite-agent artifact download --include-retried-jobs "build-report.*" ./reports/'
      - 'report_path="./reports/$(ls -v1 reports/ | tail -n 1)"'
-     - '[ -f "$$report_path" ] || echo "No report generated; "UNKNOWN ERROR" >> "$$report_path"'
+     - '[ -f "$$report_path" ] || echo "No report generated; UNKNOWN ERROR" >> "$$report_path"'
      - 'cp "$$report_path" ./claiming-report.txt'
      - 'claimable_epochs_json=$(buildkite-agent meta-data get claimable_epochs_json)'
      - 'first_epoch=$(echo "$$claimable_epochs_json" | jq ".[0]")'
      - '[[ -n "$$first_epoch" && "$$first_epoch" != "null" ]] && gcloud storage cp ./claiming-report.txt "$$gs_bucket/$$first_epoch/claiming-report.$(date +%s).txt"'
-     - 'buildkite-agent meta-data set attempts_count "$(grep -c "#ATTEMPT" ./claiming-report.txt)"'
+     - 'buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./claiming-report.txt)"'
     artifact_paths:
     - "./claiming-report.txt"
+    key: 'notification'
     depends_on: "claim-settlement"
     allow_dependency_failure: true
   
   - wait: ~
-    continue_on_failure: true
 
   - label: ":mega: Notification settlements claiming"
     commands:
@@ -137,11 +137,17 @@ steps:
       claimable_epochs=$(echo "$$claimable_epochs_json" | jq ". | join(\",\")" | tr -d '"')
       curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" \
         -F 'payload_json={
-            "content": "Claim Settlements '"$notification_result"' for epochs: '"$$claimable_epochs"' after '"$$attempts_count"' attempts",
-            "url": "'"$$BUILDKITE_BUILD_URL"'",
-            "color": "'"$$notification_color"'"
+            "embeds":[{
+              "title": "Claim Settlements '"$$notification_result"' for epochs: '"$$claimable_epochs"' after '"$$attempts_count"' attempts",
+              "url": "'"$$BUILDKITE_BUILD_URL"'",
+              "color": "'"$$notification_color"'"
+            }]
         }' \
         -F "file1=@./claiming-report.txt"
+    - |
+      build_result=$(buildkite-agent step get "outcome" --step "claim-settlement")
+    depends_on: "notification"
+    allow_dependency_failure: true
 
   - wait: ~
 
diff --git a/.buildkite/close-settlements.yml b/.buildkite/close-settlements.yml
--- a/.buildkite/close-settlements.yml
+++ b/.buildkite/close-settlements.yml
@@ -87,7 +87,7 @@ steps:
     retry:
       automatic:
         - exit_status: 100
-          limit: 10
+          limit: 5
 
   - label: "Notification setup"
     env:
@@ -96,37 +96,43 @@ steps:
      - 'mkdir ./reports'
      - 'buildkite-agent artifact download --include-retried-jobs "build-report.*" ./reports/'
      - 'report_path="./reports/$(ls -v1 reports/ | tail -n 1)"'
-     - '[ -f "$$report_path" ] || echo "No report generated; "UNKNOWN ERROR" >> "$$report_path"'
+     - '[ -f "$$report_path" ] || echo "No report generated; UNKNOWN ERROR" >> "$$report_path"'
      - 'cp "$$report_path" ./close-report.txt'
-     - 'buildkite-agent meta-data set attempts_count "$(grep -c "#ATTEMPT" ./close-report.txt)"'
+     - 'buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./close-report.txt)"'
     artifact_paths:
     - "./close-report.txt"
+    key: 'notification'
     depends_on: "close-settlement"
     allow_dependency_failure: true
-
+  
   - wait: ~
-    continue_on_failure: true
 
-  # discord reporting only in case of failure => manual intervention is needed
   - label: ":mega: Notification settlements closing"
     commands:
     - 'build_result=$(buildkite-agent step get "outcome" --step "close-settlement")'
     - |
-        if [[ "$$build_result" =~ "failed" ]]; then
-          attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
-          buildkite-agent artifact download --include-retried-jobs close-report.txt . || echo 'UNKNOWN ERROR' > './close-report.txt'
-          curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" \
-            -F 'payload_json={
-                "content": "Closed Settlements FAILURE, epoch: '"$$claimable_epochs"', '"$$attempts_count"' attempts",
-                "url": "'"$$BUILDKITE_BUILD_URL"'",
-                "color": "15158332"
-            }' \
-            -F "file1=@./close-report.txt"
-        else
-          echo "No error, no need to notify about closing settlements, all good"
-        fi
-
-    depends_on: "close-settlement"
+      if [[ -z "$$build_result" || "$$build_result" =~ "failed" ]]; then
+        notification_result="FAILED"
+        notification_color="15158332"
+      else
+        notification_result="SUCCEEDED"
+        notification_color="8388863"
+      fi
+    - |
+      attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
+      buildkite-agent artifact download --include-retried-jobs close-report.txt . || echo 'UNKNOWN ERROR' > './close-report.txt'
+      # TODO: change the discord webhook here to the correct one
+      # curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" \
+      curl "https://discord.com/api/webhooks/1237762124114296923/O-Gv1aBiB4LZy87ppR-87LPVDCBz7591Kcse52GyRUmrU-Y8IVpAjnSuP-ZwpGDLLb88" \
+        -F 'payload_json={
+            "embeds":[{
+              "title": "Close Settlements '"$$notification_result"', '"$$attempts_count"' attempts",
+              "url": "'"$$BUILDKITE_BUILD_URL"'",
+              "color": "'"$$notification_color"'"
+            }]
+        }' \
+        -F "file1=@./close-report.txt"
+    depends_on: "notification"
     allow_dependency_failure: true
 
   - wait: ~
diff --git a/.buildkite/init-settlements.yml b/.buildkite/init-settlements.yml
--- a/.buildkite/init-settlements.yml
+++ b/.buildkite/init-settlements.yml
@@ -106,7 +106,7 @@ steps:
     retry:
       automatic:
         - exit_status: 100
-          limit: 10
+          limit: 5
 
   - label: "Notification setup"
     env:
@@ -115,7 +115,7 @@ steps:
      - 'epoch=$(buildkite-agent meta-data get epoch)'
      - |
        build_result=$(buildkite-agent step get "outcome" --step "init-settlement")
-        if [[ "$$build_result" =~ "failed" ]]; then
+        if [[ -z "$$build_result" || "$$build_result" =~ "failed" ]]; then
           notification_result="FAILED"
           notification_color="15158332"
         else
@@ -128,12 +128,13 @@ steps:
      - 'mkdir ./reports'
      - 'buildkite-agent artifact download --include-retried-jobs "build-report.*" ./reports/'
      - 'report_path="./reports/$(ls -v1 reports/ | tail -n 1)"'
-     - '[ -f "$$report_path" ] || echo "No report generated; "UNKNOWN ERROR" >> "$$report_path"'
+     - '[ -f "$$report_path" ] || echo "No report generated; UNKNOWN ERROR" >> "$$report_path"'
      - 'cp "$$report_path" ./init-report.txt'
      - 'gcloud storage cp ./init-report.txt "$$gs_bucket/$$epoch/init-settlement-report.$(date +%s).txt"'
-     - 'buildkite-agent meta-data set attempts_count "$(grep -c "#ATTEMPT" ./init-report.txt)"'
+     - 'buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./init-report.txt)"'
     artifact_paths:
     - "./init-report.txt"
+    key: 'notification'
     depends_on: "init-settlement"
     allow_dependency_failure: true
 
@@ -150,11 +151,15 @@ steps:
     - |
         curl "$$DISCORD_WEBHOOK_VALIDATOR_BONDS" \
         -F 'payload_json={
-            "content": "Init Settlements '"$notification_result"' for Validator Bonds ('"$$epoch"') after '"$$attempts_count"' attempts",
-            "url": "'"$$BUILDKITE_BUILD_URL"'",
-            "color": "'"$$notification_color"'"
+            "embeds":[{
+              "title": "Init Settlements '"$notification_result"' for Validator Bonds ('"$$epoch"') after '"$$attempts_count"' attempts",
+              "url": "'"$$BUILDKITE_BUILD_URL"'",
+              "color": "'"$$notification_color"'"
+            }]
         }' \
         -F "file1=@./init-report.txt"
+    depends_on: "notification"
+    allow_dependency_failure: true
 
   - command: echo "End of concurrency gate <--"
     concurrency_group: 'validator-bonds/init-settlements'
