Institutional calculation transformed into Settlements and used in on-chain pipelines [GEN-1344] [GEN-1310] (#186)
* [institutional] handling of institutional processing

* [builkite] fixes on testing

* [buildkite] link to particular step directly

* Update settlement-distributions/institutional-distribution/README.md

Co-authored-by: martinkrecek <9853061+martinkrecek@users.noreply.github.com>

* Update .buildkite/copy-parsed-snapshot.yml

Co-authored-by: martinkrecek <9853061+martinkrecek@users.noreply.github.com>

* Update settlement-distributions/institutional-distribution/src/bin/cli.rs

Co-authored-by: martinkrecek <9853061+martinkrecek@users.noreply.github.com>

* Update .buildkite/prepare-institutional-distribution.yml

Co-authored-by: martinkrecek <9853061+martinkrecek@users.noreply.github.com>

* [review] fixes

---------

Co-authored-by: martinkrecek <9853061+martinkrecek@users.noreply.github.com>

diff --git a/.buildkite/claim-settlements.yml b/.buildkite/claim-settlements.yml
--- a/.buildkite/claim-settlements.yml
+++ b/.buildkite/claim-settlements.yml
@@ -3,6 +3,7 @@ agents:
 
 env:
   gs_bucket: gs://marinade-validator-bonds-mainnet
+  SLACK_API: https://slack.com/api/chat.postMessage
 
 steps:
   - label: ":closed_lock_with_key: Concurrency gate lock"
@@ -20,20 +21,6 @@ steps:
     artifact_paths:
       - target/release/list-claimable-epoch
       - target/release/claim-settlement
-
-  - label: ":black_nib: Find Discord webhook"
-    commands:
-    - |
-      discord_webhook=$(buildkite-agent meta-data get discord_webhook) || true
-      if [[ -z "$$discord_webhook" ]]; then
-        # env defined by job definition
-        discord_webhook="${DISCORD_WEBHOOK}"
-      fi
-      if [[ -z "$$discord_webhook" ]]; then
-        # env defined by buildkite environment
-        discord_webhook="$${DISCORD_WEBHOOK_VALIDATOR_BONDS}"
-      fi
-      buildkite-agent meta-data set discord_webhook "$$discord_webhook"
 
   - wait: ~
 
@@ -89,7 +76,10 @@ steps:
   # We need to wait for the fund-settlements trigger to get finished before we can proceed
   - label: ":gear: Upload and trigger fund-settlements pipeline"
     commands:
-      - 'buildkite-agent pipeline upload .buildkite/fund-settlements.yml'
+      - slack_feed=${SLACK_FEED:-'feed-pipeline-sam-psr'}
+      - buildkite-agent meta-data set slack_feed "$$slack_feed"
+      - export SLACK_FEED="$$slack_feed"
+      - buildkite-agent pipeline upload .buildkite/fund-settlements.yml
 
   - wait: ~
     continue_on_failure: true
@@ -173,27 +163,33 @@ steps:
 
   - label: ":mega: Notification Claiming"
     commands:
+    - buildkite-agent artifact download --include-retried-jobs claiming-report.txt . || echo "UNKNOWN ERROR" > claiming-report.txt
+    - cat ./claiming-report.txt
+    - echo '-----------------------------------------------------------------------------------'
     - source ./scripts/execute-handlers.sh
     - check_command_execution_status "claim-settlement" || true
+    - slack_feed=$(buildkite-agent meta-data get slack_feed)
     - attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
-    - buildkite-agent artifact download --include-retried-jobs claiming-report.txt . || echo "UNKNOWN ERROR" > claiming-report.txt
     - |
       claimable_epochs_json=$(buildkite-agent meta-data get claimable_epochs_json || echo "[]")
       claimable_epochs=$(echo "$$claimable_epochs_json" | jq ". | join(\",\")" | tr -d '"')
     - |
-      curl "$(buildkite-agent meta-data get discord_webhook)" \
-        -F 'payload_json={
-            "embeds":[{
-              "title": "Claim Settlements '"$$notification_result"' for epochs: '"$$claimable_epochs"' after '"$$attempts_count"' attempts",
-              "url": "'"$$BUILDKITE_BUILD_URL"'",
-              "color": "'"$$notification_color"'"
-            }]
-        }' \
-        -F "file1=@./claiming-report.txt"
-    - |
-      build_result=$(buildkite-agent step get "outcome" --step "claim-settlement")
+      curl ${SLACK_API} -X POST -H 'Content-Type: application/json; charset=utf-8' \
+        -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
+          "channel": "'"$$slack_feed"'",
+          "attachments": [
+            {
+              "color": "'"$$notification_color"'",
+              "title": "Claim Settlements '"$$notification_result"'",
+              "title_link": "'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'",
+              "text": "for epochs: '"$$claimable_epochs"' after '"$$attempts_count"' attempts",
+              "footer": "<'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'|View in Buildkite>"
+            }
+          ]
+      }'
     depends_on: "notification-setup-claim"
     allow_dependency_failure: true
+    if: "build.env('NOTIFY_FEED') == 'true'"
 
   - wait: ~
 
diff --git a/.buildkite/fund-settlements.yml b/.buildkite/fund-settlements.yml
--- a/.buildkite/fund-settlements.yml
+++ b/.buildkite/fund-settlements.yml
@@ -3,6 +3,7 @@ agents:
 
 env:
   gs_bucket: gs://marinade-validator-bonds-mainnet
+  SLACK_API: https://slack.com/api/chat.postMessage
 
 steps:
   - label: ":closed_lock_with_key: Concurrency gate lock"
@@ -12,18 +13,45 @@ steps:
 
   - wait: ~
 
+  - input: "What is slack feed to emit messages into?"
+    fields:
+      - select: "Slack feed"
+        key: "slack_feed"
+        options:
+          - label: "Feed Pipeline SAM PSR"
+            value: "feed-pipeline-sam-psr"
+          - label: "Feed Institutional Staking"
+            value: "feed-institutional-staking"
+    if: "build.env('SLACK_FEED') == null && build.env('NOTIFY_FEED') == 'true'"
+    blocked_state: running
+
+  - wait: ~
+
   - label: ":black_nib: Env variables setup: Fund Settlements"
     commands:
     - |
-      claim_type=${CLAIM_TYPE:-"$($(buildkite-agent meta-data get claim_type) || true)"}
-      if [[ -n "$$claim_type" ]]; then
-        buildkite-agent meta-data set claim_type "$$claim_type"
-      fi
-    - |
-      epoch=${EPOCH:-"$($(buildkite-agent meta-data get epoch) || true)"}
+      epoch=${EPOCH:-$(buildkite-agent meta-data get epoch || echo "")}
       if [[ -n "$$epoch" ]]; then
         buildkite-agent meta-data set epoch "$$epoch"
+      else
+        unset epoch
       fi
+    - |
+      claim_type=${CLAIM_TYPE:-$(buildkite-agent meta-data get claim_type || echo "")}
+      if [[ -n "$$claim_type" ]]; then
+        buildkite-agent meta-data set claim_type "$$claim_type"
+      else
+        unset claim_type
+      fi
+    - |
+      slack_feed=${SLACK_FEED:-$(buildkite-agent meta-data get slack_feed || echo "")}
+      if [[ -n "$$slack_feed" ]]; then
+        buildkite-agent meta-data set slack_feed "$$slack_feed"
+      else
+        unset slack_feed
+      fi
+    - |
+      echo "Epoch: '$$epoch', Claim Type: '$$claim_type', Slack Feed: '$$slack_feed'"
 
   - wait: ~
 
@@ -85,20 +113,6 @@ steps:
     artifact_paths:
       - "./merkle-trees/**/*"
 
-  - label: ":black_nib: Find Discord webhook"
-    commands:
-    - |
-      discord_webhook=$(buildkite-agent meta-data get discord_webhook) || true
-      if [[ -z "$$discord_webhook" ]]; then
-        # env defined by job definition
-        discord_webhook="${DISCORD_WEBHOOK}"
-      fi
-      if [[ -z "$$discord_webhook" ]]; then
-        # env defined by buildkite environment
-        discord_webhook="$${DISCORD_WEBHOOK_VALIDATOR_BONDS}"
-      fi
-      buildkite-agent meta-data set discord_webhook "$$discord_webhook"
-
   - wait: ~
 
   - label: ":campfire::arrow_right: Fund settlements"
@@ -131,7 +145,7 @@ steps:
     - |
       handle_command_execution "$$command_name" \
       ./target/release/fund-settlement \
-        --rpc-url $$RPC_URL \
+        --rpc-url "$$RPC_URL" \
         --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
         --fee-payer "$$PSR_TX_FEE_WALLET" \
         --marinade-wallet "$$PSR_MARINADE_DAO_FUNDER_WALLET" \
@@ -176,26 +190,30 @@ steps:
 
   - label: ":mega: Notification Funding"
     commands:
+    - buildkite-agent artifact download --include-retried-jobs fund-report.txt . || echo 'UNKNOWN ERROR' > './fund-report.txt'
+    - cat ./fund-report.txt
+    - echo "--------------------------------------------\n\n"
     - source ./scripts/execute-handlers.sh
     - check_command_execution_status "fund-settlement" || true
     - |
-      attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
       claim_type=$(buildkite-agent meta-data get claim_type) || true
-      if [[ -n "$$claim_type" ]]; then
-        claim_type=" [$$claim_type]"
-      fi
-      buildkite-agent artifact download --include-retried-jobs fund-report.txt . || echo 'UNKNOWN ERROR' > './fund-report.txt'
-      curl "$(buildkite-agent meta-data get discord_webhook)" \
-        -F 'payload_json={
-            "embeds":[{
-              "title": "Fund Settlements '"$${notification_result}$${claim_type}"', '"$$attempts_count"' attempts",
-              "url": "'"$$BUILDKITE_BUILD_URL"'",
-              "color": "'"$$notification_color"'"
-            }]
-        }' \
-        -F "file1=@./fund-report.txt"
+      [[ -n "$$claim_type" ]] && claim_type=" [$$claim_type]"
+    - slack_feed=$(buildkite-agent meta-data get slack_feed)
+    - attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
+    - |
+      curl $SLACK_API -X POST -H 'Content-Type: application/json; charset=utf-8' \
+        -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
+        "channel": "'"$$slack_feed"'",
+        "attachments": [{
+          "color": "'"$$notification_color"'",
+          "title": "Fund Settlements '"$${notification_result}$${claim_type}"', '"$$attempts_count"' attempts",
+          "title_link": "'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'",
+          "footer": "<'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'|View in Buildkite>" 
+        }]
+      }'
     depends_on: "notification-setup-funding"
     allow_dependency_failure: true
+    if: "build.env('NOTIFY_FEED') == 'true'"
 
   - wait: ~
 
diff --git a/.buildkite/init-settlements.yml b/.buildkite/init-settlements.yml
--- a/.buildkite/init-settlements.yml
+++ b/.buildkite/init-settlements.yml
@@ -3,6 +3,7 @@ agents:
 
 env:
   gs_bucket: gs://marinade-validator-bonds-mainnet
+  SLACK_API: https://slack.com/api/chat.postMessage
 
 steps:
   # epoch number provided in ENV and then waiting for confirmation to proceed
@@ -13,8 +14,7 @@ steps:
         key: "epoch"
         format: "[0-9]+"
     if: "build.env('EPOCH') == null"
-  - command: "echo 'Epoch is: $EPOCH'"
-    if: "build.env('EPOCH') != null"
+    blocked_state: running
 
   - input: "What is the claim type to init?"
     fields:
@@ -25,22 +25,33 @@ steps:
             value: "bid-psr-distribution"
           - label: "Bid Distribution"
             value: "bid-distribution"
+          - label: "Institutional Distribution"
+            value: "institutional-distribution"
     if: "build.env('CLAIM_TYPE') == null"
+    blocked_state: running
 
   - wait: ~
 
   - label: ":black_nib: Env variables setup: Init Settlements"
     commands:
     - |
-      discord_webhook="${DISCORD_WEBHOOK:-$$DISCORD_WEBHOOK_VALIDATOR_BONDS}"
-      buildkite-agent meta-data set discord_webhook "$$discord_webhook"
-    - |
       epoch=${EPOCH:-$(buildkite-agent meta-data get epoch)}
       buildkite-agent meta-data set epoch "$$epoch"
     - |
       claim_type=${CLAIM_TYPE:-$(buildkite-agent meta-data get claim_type)}
       buildkite-agent meta-data set claim_type "$$claim_type"
-    - 'echo "Epoch: $$epoch", Claim Type: $$claim_type'
+    - |
+      slack_feed=${SLACK_FEED:-$(buildkite-agent meta-data get slack_feed || echo "")}
+      if [[ -z "$$slack_feed" ]]; then
+        if [[ "$$claim_type" =~ ^"bid-".* ]]; then
+          slack_feed="feed-pipeline-sam-psr"
+        else
+          slack_feed="feed-institutional-staking"
+        fi
+      fi
+      buildkite-agent meta-data set slack_feed "$$slack_feed"
+    - |
+      echo "Epoch: '$$epoch', Claim Type: '$$claim_type', Slack Feed: '$$slack_feed'"
 
   - wait: ~
 
@@ -48,18 +59,22 @@ steps:
     commands:
     - epoch=$(buildkite-agent meta-data get epoch)
     - claim_type=$(buildkite-agent meta-data get claim_type)
+    - slack_feed=$(buildkite-agent meta-data get slack_feed)
     - |
-      curl "$(buildkite-agent meta-data get discord_webhook)" \
-        -H "Content-Type: application/json" -d '{
-        "embeds": [
-          {
-            "title": "Confirm Settlements Initialization for Validator Bonds ('"$$epoch"')/('"$$claim_type"').",
-            "description": "Please review the 'Unblock' if ready to proceed.",
-            "url": "'"$$BUILDKITE_BUILD_URL"'",
-            "color": "8388863"
-          }
-        ]
+      curl $SLACK_API -X POST -H 'Content-Type: application/json; charset=utf-8' \
+        -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
+          "channel": "'"$$slack_feed"'",
+          "attachments": [
+            {
+              "color": "#8000ff",
+              "title": "Confirm Settlements Initialization for Validator Bonds ('"$$epoch"')/('"$$claim_type"')",
+              "title_link": "'"$$BUILDKITE_BUILD_URL"'",
+              "text": "Please review the *'"'"'Unblock'"'"'* if ready to proceed",
+              "footer": "<'"$$BUILDKITE_BUILD_URL"'|View in Buildkite>"
+            }
+          ]
       }'
+    if: "build.env('NOTIFY_FEED') == 'true'"
 
   - wait: ~
 
@@ -99,7 +114,7 @@ steps:
 
   - label: ":closed_lock_with_key: Concurrency gate lock"
     command: echo "--> Start of concurrency gate"
-    concurrency_group: 'validator-bonds/init-settlements${CLAIM_TYPE}'
+    concurrency_group: 'validator-bonds/init-settlements-${CLAIM_TYPE}'
     concurrency: 1
 
   - wait: ~
@@ -122,8 +137,9 @@ steps:
     - buildkite-agent artifact download --include-retried-jobs settlement-merkle-trees.json .
     - buildkite-agent artifact download --include-retried-jobs settlements.json .
     - chmod +x target/release/init-settlement
+    - source ./scripts/execute-handlers.sh
     - |
-      set -o pipefail
+      handle_command_execution "$$command_name" \
       ./target/release/init-settlement \
         --rpc-url $$RPC_URL \
         --input-merkle-tree-collection "./settlement-merkle-trees.json" \
@@ -131,7 +147,7 @@ steps:
         --operator-authority "$$VALIDATOR_BONDS_OPERATOR_AUTHORITY" \
         --fee-payer "$$PSR_TX_FEE_WALLET" \
         --rent-payer "$$PSR_RENT_PAYER_WALLET" \
-        --epoch "$$epoch" | tee -a "./execution-report.$$command_name.$$BUILDKITE_RETRY_COUNT"
+        --epoch "$$epoch"
     key: 'init-settlement'
     artifact_paths:
     - "./execution-report.*"
@@ -142,19 +158,6 @@ steps:
 
   - label: ":memo: Notification setup: Init Settlements"
     commands:
-     - 'epoch=$(buildkite-agent meta-data get epoch)'
-     - |
-        build_result=$(buildkite-agent step get "outcome" --step "init-settlement")
-        if [[ -z "$$build_result" || "$$build_result" =~ "failed" ]]; then
-          notification_result="FAILED"
-          notification_color="15158332"
-        else
-          notification_result="SUCCEEDED"
-          notification_color="52224"
-        fi
-     - buildkite-agent meta-data set notification_color "$$notification_color"
-     - buildkite-agent meta-data set notification_result "$$notification_result"
-     - 'echo "Notification result: $$notification_result, color: $$notification_color"'
      - mkdir ./reports
      - command_name='init-settlement'
      - buildkite-agent artifact download --include-retried-jobs "execution-report.$$command_name.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.$$command_name.error
@@ -180,26 +183,34 @@ steps:
 
   - label: ":mega: Notification :fast_forward: Monitoring Initialize Settlements"
     commands:
+    - buildkite-agent artifact download --include-retried-jobs init-report.txt . || echo "UNKNOWN ERROR" > init-report.txt
+    - cat ./init-report.txt
+    - echo "--------------------------------------------\n\n"
+    - source ./scripts/execute-handlers.sh
+    - check_command_execution_status "init-settlement" || true
     - epoch=$(buildkite-agent meta-data get epoch)
-    - notification_result=$(buildkite-agent meta-data get notification_result || echo "UNKNOWN")
-    - notification_color=$(buildkite-agent meta-data get notification_color || echo "15158332")
+    - slack_feed=$(buildkite-agent meta-data get slack_feed)
     - attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
     - claim_type=$(buildkite-agent meta-data get claim_type || echo "UNKNOWN")
-    - buildkite-agent artifact download --include-retried-jobs init-report.txt . || echo "UNKNOWN ERROR" > init-report.txt
     - |
-        curl "$(buildkite-agent meta-data get discord_webhook)" \
-        -F 'payload_json={
-            "embeds":[{
-              "title": "Init Settlements '"$$notification_result"' for '"$$claim_type"' Validator Bonds ('"$$epoch"') after '"$$attempts_count"' attempts",
-              "url": "'"$$BUILDKITE_BUILD_URL"'",
-              "color": "'"$$notification_color"'"
-            }]
-        }' \
-        -F "file1=@./init-report.txt"
+      curl $SLACK_API -X POST -H 'Content-Type: application/json; charset=utf-8' \
+        -H "Authorization: Bearer $$SLACK_BEARER_TOKEN" -d '{
+        "channel": "'"$$slack_feed"'",
+        "attachments": [
+          {
+            "color": "'"$$notification_color"'",
+            "title": "Init Settlements ('"$$claim_type"'): '"$$notification_result"'",
+            "title_link": "'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'",
+            "text": "'"$$claim_type"' Init Settlements Validator Bonds ('"$$epoch"') after '"$$attempts_count"' attempts",
+            "footer": "<'"$${BUILDKITE_BUILD_URL}/#$${BUILDKITE_JOB_ID}"'|View in Buildkite>"
+          }
+        ]
+      }'
     depends_on: "notification-setup-init"
     allow_dependency_failure: true
+    if: "build.env('NOTIFY_FEED') == 'true'"
 
-  - label: ":mega: Notification :fast_forward: PSR feed"
+  - label: ":mega: Notification :fast_forward: Discord PSR feed"
     commands:
     - claim_type=$(buildkite-agent meta-data get claim_type)
     - epoch=$(buildkite-agent meta-data get epoch)
@@ -215,16 +226,20 @@ steps:
       done
     depends_on: "notification-setup-init"
     allow_dependency_failure: true
-    if: "build.env('NOTIFY_PSR_FEED') != null"
+    if: "build.env('NOTIFY_DISCORD_FEED') != null"
 
   - wait: ~
     continue_on_failure: true
 
-  - label: ":gear: Upload and trigger fund-settlements pipeline"
+  - label: ":gear: Upload and get running fund-settlements pipeline"
     commands:
       - epoch=$(buildkite-agent meta-data get epoch)
       - claim_type=$(buildkite-agent meta-data get claim_type)
-      - 'echo "Epoch: $$epoch, Claim type: $$claim_type"'
+      - slack_feed=$(buildkite-agent meta-data get slack_feed)
+      - export EPOCH="$$epoch"
+      - export CLAIM_TYPE="$$claim_type"
+      - export SLACK_FEED="$$slack_feed"
+      - 'echo "Epoch: $$epoch, Claim type: $$claim_type, Slack Feed: $$slack_feed"'
       - buildkite-agent pipeline upload .buildkite/fund-settlements.yml
     depends_on: "init-settlement"
     allow_dependency_failure: true
@@ -233,5 +248,5 @@ steps:
 
   - label: ":unlock: Concurrency gate unlock"
     command: echo "End of concurrency gate <--"
-    concurrency_group: 'validator-bonds/init-settlements${CLAIM_TYPE}'
+    concurrency_group: 'validator-bonds/init-settlements-${CLAIM_TYPE}'
     concurrency: 1
