[buildkite] init settlement to report claim type

diff --git a/.buildkite/fund-settlements.yml b/.buildkite/fund-settlements.yml
--- a/.buildkite/fund-settlements.yml
+++ b/.buildkite/fund-settlements.yml
@@ -146,11 +146,11 @@ steps:
 
   - label: ":memo: Notification setup: Fund Settlements"
     commands:
-     - 'mkdir ./reports'
-     - 'buildkite-agent artifact download --include-retried-jobs "execution-report.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report.error'
-     - 'report_path="./reports/$(ls -v1 reports/ | tail -n 1)"'
-     - 'cp "$$report_path" ./fund-report.txt'
-     - 'buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./fund-report.txt)"'
+     - mkdir ./reports
+     - buildkite-agent artifact download --include-retried-jobs "execution-report-fund.*" ./reports/ || echo "No report ERROR" > ./reports/execution-report-fund.error
+     - report_path="./reports/$(ls -v1 reports/ | tail -n 1)"
+     - cp "$$report_path" ./fund-report.txt
+     - buildkite-agent meta-data set attempts_count "$(grep -c ATTEMPT ./fund-report.txt)"
     artifact_paths:
     - "./fund-report.txt"
     key: 'notification-setup-funding'
@@ -178,11 +178,15 @@ steps:
     - check_command_execution_status "fund-settlement" || true
     - |
       attempts_count=$(buildkite-agent meta-data get attempts_count || echo "UNKNOWN")
+      claim_type=$(buildkite-agent meta-data get claim_type) || true
+      if [[ -n "$$claim_type" ]]; then
+        claim_type=" [$$claim_type]"
+      fi
       buildkite-agent artifact download --include-retried-jobs fund-report.txt . || echo 'UNKNOWN ERROR' > './fund-report.txt'
       curl "$(buildkite-agent meta-data get discord_webhook)" \
         -F 'payload_json={
             "embeds":[{
-              "title": "Fund Settlements '"$$notification_result"', '"$$attempts_count"' attempts",
+              "title": "Fund Settlements '"$${notification_result}$${claim_type}"', '"$$attempts_count"' attempts",
               "url": "'"$$BUILDKITE_BUILD_URL"'",
               "color": "'"$$notification_color"'"
             }]
