a

diff --git a/.buildkite/fund-settlements.yml b/.buildkite/fund-settlements.yml
--- a/.buildkite/fund-settlements.yml
+++ b/.buildkite/fund-settlements.yml
@@ -136,7 +136,9 @@ steps:
         --marinade-wallet "$$PSR_MARINADE_DAO_FUNDER_WALLET" \
         --rent-payer "$$PSR_RENT_PAYER_WALLET" \
         $$files
+    - ls -la
     - cat "./execution-report.$${command_name}.$$BUILDKITE_RETRY_COUNT" >> "./execution-report.$${command_name}"
+    - ls -la
     key: 'fund-settlement'
     artifact_paths:
       - "./execution-report*"
@@ -148,10 +150,10 @@ steps:
   - label: ":memo: Notification setup: Fund Settlements"
     commands:
      - buildkite-agent artifact download "execution-report.$$command_name" . || echo "No report ERROR" > ./execution-report.$$command_name
-     - cp "./execution-report.$$command_name" "./cummulative-report.txt"
-     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c 'ATTEMPT' ./cummulative-report.txt || echo '0')"
+     - cp "./execution-report.$$command_name" "./cumulative-report.txt"
+     - buildkite-agent meta-data set --redacted-vars="" attempts_count "$(grep -c 'ATTEMPT' ./cumulative-report.txt || echo '0')"
     artifact_paths:
-      - "./cummulative-report.txt"
+      - "./cumulative-report.txt"
     key: 'notification-setup-funding'
     depends_on: "fund-settlement"
     allow_dependency_failure: true
@@ -186,10 +188,10 @@ steps:
     - latest_funded_epoch=$(buildkite-agent meta-data get latest_funded_epoch) || true
     - claim_type=$(buildkite-agent meta-data get claim_type) || true
     - claim_type_prefix=$([[ -z "$$claim_type" ]] && echo "" || echo "$${claim_type}-")
-    - buildkite-agent artifact download cummulative-report.txt . || echo "UNKNOWN ERROR" > ./cummulative-report.txt
+    - buildkite-agent artifact download cumulative-report.txt . || echo "UNKNOWN ERROR" > ./cumulative-report.txt
     - |
       if [[ -n "$$latest_funded_epoch" && $(gcloud storage ls "$gs_bucket/$$latest_funded_epoch" 2> /dev/null) ]]; then
-        gcloud storage cp ./cummulative-report.txt "$gs_bucket/$$latest_funded_epoch/buildkite/$${claim_type_prefix}$${command_name}-report.$(date +%s).txt"
+        gcloud storage cp ./cumulative-report.txt "$gs_bucket/$$latest_funded_epoch/buildkite/$${claim_type_prefix}$${command_name}-report.$(date +%s).txt"
       fi
     depends_on: "notification-setup-funding"
     allow_dependency_failure: true
